services:
  web:
    image: nginx:1.27.0
    ports:
      - 80:80
      - 443:443
      - 4000:4000
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    volumes:
      - ./client:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - posts_db
      - newsletter_db
  api:
    image: denoland/deno:ubuntu-1.44.4
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    working_dir: /server
    command: deno task run
    depends_on:
      - posts_db
      - newsletter_db
  posts_db:
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verylongpassword
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  newsletter_db:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    ports:
      - 27017:27017

volumes:
  postgres_data:


configs:
  nginx_conf:
    file: ./configs/nginx.conf
