name: deploy to AWS LightSail
on: [push]
jobs:
  deploy-to-server
    runs-on: ubuntu-latest
    steps:
      - name: setting up
        with:
        env:
          mailgun_api_key: ${{secrets.MAILGUN_API_KEY}}
      - uses: actions/checkout@v4
      - run: 